const FETCH_HEROES = 'FETCH_HEROES';
const FETCH_HEROES_SUCCESS = 'FETCH_HEROES_SUCCESS';
const FETCH_HEROES_SAGA = 'FETCH_HEROES_SAGA';
const SORT_HEROES = 'SORT_HEROES';
const FETCH_COMMICS = 'FETCH_COMMICS';
const FETCH_COMMICS_SUCCESS = 'FETCH_COMMICS_SUCCESS';
const FETCH_ERROR = 'FETCH_COMMICS_ERROR';
const FETCH_COMMICS_SAGA = 'FETCH_COMMICS_SAGA';

export {
  FETCH_HEROES,
  FETCH_HEROES_SUCCESS,
  FETCH_HEROES_SAGA,
  SORT_HEROES,
  FETCH_COMMICS,
  FETCH_COMMICS_SUCCESS,
  FETCH_ERROR,
  FETCH_COMMICS_SAGA,
};
